### ISSUE TITLE
Project is not working

### ISSUE THREAD

**Issue by singhanuj620** [atskimura/peerjs-examples-heroku#1]
Have opened in chrome desktop, allowed the camera and mic permissions, but still nothing showed up
![Proof](https://user-images.githubusercontent.com/30296527/88513717-6fa9c680-d006-11ea-933f-055e41df78d1.png)

**Comment by atskimura** [comment]
This repository is seven years old. I can't guarantee it will work now, and I don't plan to maintain it anymore. I'm sorry, could you fork it and fix it?

**Comment by singhanuj620** [comment]
I am having issue with deployment. My bad, haven't seen the timeline. You can remove the issue.
